### PR TITLE
Implement Auto Complete

### PR DESCRIPTION
**Pull request by mgoo**
Also tidied HTML and fixed the examples select

### CODE REVIEW

**Comment by DavePearce** [comment]
Hey Andrew,

Ok, looks interesting.  Especially the autocomplete and fixing that Chrome bug --- thanks!!  In general, I'm not a fan of templates.  It just makes things more complicated, and I like everything just in Java.  Anyhow, all good for now.  I haven't used freemarker before ... I'll take a look.

**Comment by DavePearce** [comment]
Hey,

Ok, so what does autocomplete actually do?  I can't see it doing anything, unless I missed something?

**Comment by mgoo** [comment]
when you start typing one of the key words like function and you get half way through pressing ctrl + space should bring up a little box with the word function in it.
screenshot from 2017-10-23 11-30-46

**Comment by DavePearce** [comment]
Hey,

Yeah that's what I thought. But it wasn't what I was seeing. I'll try again later.

D


--
Senior Lecturer in Computer Science,
School of Engineering and Computer Science,
Victoria University of Wellington,
PO Box 600,
Wellington,
New Zealand.

Office: Cotton 231
Phone: +64 (0)4 4635833
URL: http://ecs.victoria.ac.nz/~djp

**Comment by DavePearce** [comment]
Ok, fixed.  I added this:
```
    editor.setOptions({
        ...
	enableLiveAutocompletion: true,
        ...
    });
```

**Pull request merged**
