### PR TITLE
Increase base code view size

### PR DESCRIPTION
**Pull request by dylan-chong**
I see there is a jquery resizeable call in the javascript code, I probably don't have the time to fix it though

### CODE REVIEW

**Comment by DavePearce** [comment]
On firefox you can use the resizer widget in the botton right corner.  But there is some odd bug in where the ACE editor doesn't recognise this somehow.  I haven't figured it out.

**Comment by dylan-chong** [comment]
Strange this doesn't work on chrome or safari....

**Comment by DavePearce** [comment]
yeah, I'm not quite sure why not.  I need to investigate it properly ...

**Comment by dylan-chong** [comment]
Oh well, this PR can be a temporary fix anyway

**Pull request merged**
